<?php
namespace aura\web;
use aura\di\Config;
use aura\di\Forge;

/**
 * Test class for ControllerFactory.
 * Generated by PHPUnit on 2011-03-19 at 15:01:06.
 */
class ControllerFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ControllerFactory
     */
    protected $factory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->factory = $this->newFactory();
    }

    protected function newFactory($map = null, $not_found = null)
    {
        return new ControllerFactory(
            new Forge(new Config),
            $map,
            $not_found
        );
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testNewInstance().
     */
    public function testNewInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
