<?php
namespace aura\web;

/**
 * Test class for ResponseTransfer.
 * Generated by PHPUnit on 2011-05-02 at 10:30:39.
 */
class ResponseTransferTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResponseTransfer
     */
    protected $response;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->response = new ResponseTransfer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement test__get().
     */
    public function test__get()
    {
        $this->response->view_data->foo = 'bar';
        $this->assertSame('bar', $this->response->view_data['foo']);
        
        $this->response->layout_data->zim = 'gir';
        $this->assertSame('gir', $this->response->layout_data['zim']);
    }
    
    public function test__getNoSuchKey()
    {
        $this->setExpectedException('aura\web\Exception');
        $foo = $this->response->foo;
    }
    
    /**
     * @todo Implement testSetCache().
     */
    public function testSetAndGetCache()
    {
        // "add headers to turn off caching"
        $this->response->setCache(false);
        $this->assertFalse($this->response->getCache());
        $expect = array (
          'Pragma' => 'no-cache',
          'Cache-Control' => array (
            'no-store, no-cache, must-revalidate',
            'post-check=0, pre-check=0',
          ),
          'Expires' => '1',
        );
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
        
        // "do not add cache-related headers"
        $this->response->setCache(null);
        $this->assertNull($this->response->getCache());
        $expect = array();
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
        
        // "undefined"
        $this->response->setCache(true);
        $this->assertTrue($this->response->getCache());
        $expect = array();
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetContent().
     */
    public function testSetAndGetContent()
    {
        $expect = 'foo bar baz';
        $this->response->setContent($expect);
        $actual = $this->response->getContent();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetContentType().
     */
    public function testSetAndGetContentType()
    {
        $expect = 'application/json';
        $this->response->setContentType($expect);
        $actual = $this->response->getContentType();
        $this->assertSame($expect, $actual);
        
        $expect = array (
          'Content-Type' => 'application/json',
        );
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetCookie().
     */
    public function testSetAndGetCookie()
    {
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        
        $expect = array (
          'value' => 'bar',
          'expire' => $expire,
          'path' => '/path',
          'domain' => 'example.com',
          'secure' => false,
          'httponly' => true,
        );

        $actual = $this->response->getCookie('foo');
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testGetCookies().
     */
    public function testGetCookies()
    {
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        $this->response->setCookie('baz', 'dib', date('Y-m-d H:i:s', $expire), '/path', 'example.com');
        
        $expect = array (
            'foo' => array(
              'value' => 'bar',
              'expire' => $expire,
              'path' => '/path',
              'domain' => 'example.com',
              'secure' => false,
              'httponly' => true,
            ),
            'baz' => array(
              'value' => 'dib',
              'expire' => $expire,
              'path' => '/path',
              'domain' => 'example.com',
              'secure' => false,
              'httponly' => true,
            ),
        );

        $actual = $this->response->getCookies();
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetCookiesHttponly().
     */
    public function testSetCookiesHttponly()
    {
        $this->response->setCookiesHttponly(false);
        
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        
        $expect = array (
          'value' => 'bar',
          'expire' => $expire,
          'path' => '/path',
          'domain' => 'example.com',
          'secure' => false,
          'httponly' => false,
        );

        $actual = $this->response->getCookie('foo');
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetHeader().
     */
    public function testSetHeader()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->setHeader('dib', 'zim');
        
        $expect = array(
            'Foo-Bar' => 'baz',
            'Dib' => 'zim',
        );
        
        $actual = $this->response->getHeaders();
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testAddHeader().
     */
    public function testAddHeader()
    {
        $this->response->addHeader('foo', 'bar');
        $this->response->addHeader('foo', 'baz');
        $this->response->addHeader('foo', 'dib');
        
        $expect = array(
            'Foo' => array('bar', 'baz', 'dib'),
        );
        
        $actual = $this->response->getHeaders();
        
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testGetHeader().
     */
    public function testGetHeader()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->addHeader('dib', 'zim');
        $this->response->addHeader('dib', 'gir');
        
        $expect = 'baz';
        $actual = $this->response->getHeader('foo-bar');
        $this->assertSame($expect, $actual);
        
        $expect = array('zim', 'gir');
        $actual = $this->response->getHeader('dib');
        $this->assertSame($expect, $actual);
        
        // no such header
        $this->assertNull($this->response->getHeader('no-such-header'));
    }

    /**
     * @todo Implement testGetHeaders().
     */
    public function testGetHeaders()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->addHeader('dib', 'zim');
        $this->response->addHeader('dib', 'gir');
        
        $expect = array (
          'Foo-Bar' => 'baz',
          'Dib' => 
          array (
            0 => 'zim',
            1 => 'gir',
          ),
        );
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetRedirect().
     */
    public function testRedirect()
    {
        $this->assertFalse($this->response->isRedirect());
        $this->response->setRedirect('http://example.com');
        $this->assertTrue($this->response->isRedirect());
        
        $expect = 'http://example.com';
        $actual = $this->response->getRedirect();
        $this->assertSame($expect, $actual);
        
        $expect = array (
          'Location' => 'http://example.com',
        );
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }
    
    /**
     * @todo Implement testSetRedirectAfterPost().
     */
    public function testRedirectAfterPost()
    {
        $this->assertFalse($this->response->isRedirect());
        $this->response->setRedirectAfterPost('http://example.com');
        $this->assertTrue($this->response->isRedirect());
        
        $expect = 'http://example.com';
        $actual = $this->response->getRedirect();
        $this->assertSame($expect, $actual);
        
        $expect = array (
          'Pragma' => 'no-cache',
          'Cache-Control' => 
          array (
            0 => 'no-store, no-cache, must-revalidate',
            1 => 'post-check=0, pre-check=0',
          ),
          'Expires' => '1',
          'Location' => 'http://example.com',
        );
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetStatusCode().
     */
    public function testSetAndGetStatusCode()
    {
        $expect = 404;
        $this->response->setStatusCode($expect);
        $actual = $this->response->getStatusCode();
        $this->assertSame($expect, $actual);
    }
    
    public function testSetStatusCodeWrong()
    {
        $this->setExpectedException('aura\web\Exception');
        $this->response->setStatusCode('88');
    }
    
    /**
     * @todo Implement testSetStatusText().
     */
    public function testSetAndGetStatusText()
    {
        $expect = 'Not Found';
        $this->response->setStatusText($expect);
        $actual = $this->response->getStatusText();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetVersion().
     */
    public function testSetAndGetVersion()
    {
        $expect = '1.1';
        $this->response->setVersion($expect);
        $actual = $this->response->getVersion();
        $this->assertSame($expect, $actual);
    }

    public function testVersionWrong()
    {
        $this->setExpectedException('aura\web\Exception');
        $this->response->setVersion('88');
    }
    
    /**
     * @todo Implement testSetView().
     */
    public function testSetAndGetView()
    {
        $expect = 'foo';
        $this->response->setView($expect);
        $actual = $this->response->getView();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetViewData().
     */
    public function testSetAndGetViewData()
    {
        $expect = array(
            'foo' => 'bar',
        );
        $this->response->setViewData($expect);
        $actual = $this->response->getViewData();
        $this->assertSame($expect, $actual);
    }

    public function testAddAndGetViewStack()
    {
        $expect = array(
            array('vendor\package', 'view'),
        );
        $this->response->addViewStack('vendor\package');
        $actual = $this->response->getViewStack();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetLayout().
     */
    public function testSetAndGetLayout()
    {
        $expect = 'foo';
        $this->response->setLayout($expect);
        $actual = $this->response->getLayout();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetLayoutData().
     */
    public function testSetAndGetLayoutData()
    {
        $expect = array(
            'foo' => 'bar',
        );
        $this->response->setLayoutData($expect);
        $actual = $this->response->getLayoutData();
        $this->assertSame($expect, $actual);
    }

    public function testAddAndGetLayoutStack()
    {
        $expect = array(
            array('vendor\package', 'layout'),
        );
        $this->response->addLayoutStack('vendor\package');
        $actual = $this->response->getLayoutStack();
        $this->assertSame($expect, $actual);
    }

    public function testSetAndGetLayoutContentVar()
    {
        $expect = 'my_content_var';
        $this->response->setLayoutContentVar($expect);
        $actual = $this->response->getLayoutContentVar();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testSetFormat().
     */
    public function testSetAndGetFormat()
    {
        $expect = '.json';
        $this->response->setFormat($expect);
        $actual = $this->response->getFormat();
        $this->assertSame($expect, $actual);
    }

    /**
     * @todo Implement testNegotiateContentType().
     */
    public function testNegotiateContentType_alreadySet()
    {
        $type = 'application/json';
        $this->response->setContentType($type);
        $this->assertNull($this->response->negotiateContentType());
        $this->assertSame($type, $this->response->getContentType());
    }

    public function testNegotiateContentType_byFormat()
    {
        $type = 'application/json';
        $this->response->setFormat('.json');
        $this->assertTrue($this->response->negotiateContentType());
        $this->assertSame($type, $this->response->getContentType());
    }

    public function testNegotiateContentType_byView()
    {
        $type = 'application/json';
        
        $accept = array(
            '1.0' => 'application/json',
        );
        
        $this->response->setView(array(
            'text/html'        => 'view',
            'application/json' => 'view.json',
            'application/xml'  => 'view.xml',
        ));
        
        $this->assertTrue($this->response->negotiateContentType($accept));
        $this->assertSame($type, $this->response->getContentType());
    }

    public function testNegotiateContentType_byLayout()
    {
        $type = 'application/json';
        
        $accept = array(
            '1.0' => 'application/json',
        );
        
        $this->response->setLayout(array(
            'text/html'        => 'view',
            'application/json' => 'view.json',
            'application/xml'  => 'view.xml',
        ));
        
        $this->assertTrue($this->response->negotiateContentType($accept));
        $this->assertSame($type, $this->response->getContentType());
    }

    public function testNegotiateContentType_noAcceptableType()
    {
        $type = 'application/json';
        
        $accept = array(
            '1.0' => 'application/json',
        );
        
        $this->response->setView(array(
            'text/html'        => 'view',
            'application/xml'  => 'view.xml',
        ));
        
        $this->response->setLayout(array(
            'text/html'        => 'view',
            'application/xml'  => 'view.xml',
        ));
        
        $this->assertFalse($this->response->negotiateContentType());
    }
    
    /**
     * @todo Implement testMatchView().
     */
    public function testMatchView_null()
    {
        $this->assertNull($this->response->matchView());
    }
    
    public function testMatchView_string()
    {
        $expect = 'view.json';
        $this->response->setView($expect);
        $actual = $this->response->matchView();
        $this->assertSame($expect, $actual);
    }
    
    public function testMatchView_closure()
    {
        $this->response->view_data->foo = 'bar';
        $this->response->setView(function($response) {
            return $response->view_data->foo;
        });
        $actual = $this->response->matchView();
        $this->assertSame('bar', $actual);
    }
    
    public function testMatchView_arrayString()
    {
        $this->response->setContentType('application/json');
        
        $this->response->setView(array(
            'text/html'        => 'view',
            'application/json' => 'view.json',
            'application/xml'  => 'view.xml',
        ));
        
        $expect = 'view.json';
        $actual = $this->response->matchView();
        $this->assertSame($expect, $actual);
    }

    public function testMatchView_arrayClosure()
    {
        $this->response->setContentType('application/xml');
        
        $this->response->view_data->foo = 'bar';
        
        $this->response->setView(array(
            'text/html'        => 'view',
            'application/json' => 'view.json',
            'application/xml'  => function($response) {
                return $response->view_data->foo;
            },
        ));
        
        $actual = $this->response->matchView();
        $this->assertSame('bar', $actual);
    }

    public function testMatchView_noAcceptableView()
    {
        $this->setExpectedException('aura\web\Exception_NoAcceptableView');
        
        $this->response->setContentType('application/xhtml+xml');
        
        $this->response->setView(array(
            'text/html'        => 'view',
            'application/json' => 'view.json',
            'application/xml'  => 'view.xml',
        ));
        
        $this->response->matchView();
    }
    
    /**
     * @todo Implement testMatchLayout().
     */
    public function testMatchLayout_null()
    {
        $this->assertNull($this->response->matchLayout());
    }
    
    public function testMatchLayout_string()
    {
        $expect = 'layout.json';
        $this->response->setLayout($expect);
        $actual = $this->response->matchLayout();
        $this->assertSame($expect, $actual);
    }
    
    public function testMatchLayout_closure()
    {
        $this->response->layout_data->foo = 'bar';
        $this->response->setLayout(function($response) {
            return $response->layout_data->foo;
        });
        $actual = $this->response->matchLayout();
        $this->assertSame('bar', $actual);
    }
    
    public function testMatchLayout_arrayString()
    {
        $this->response->setContentType('application/json');
        
        $this->response->setLayout(array(
            'text/html'        => 'layout',
            'application/json' => 'layout.json',
            'application/xml'  => 'layout.xml',
        ));
        
        $expect = 'layout.json';
        $actual = $this->response->matchLayout();
        $this->assertSame($expect, $actual);
    }

    public function testMatchLayout_arrayClosure()
    {
        $this->response->setContentType('application/xml');
        
        $this->response->layout_data->foo = 'bar';
        
        $this->response->setLayout(array(
            'text/html'        => 'layout',
            'application/json' => 'layout.json',
            'application/xml'  => function($response) {
                return $response->layout_data->foo;
            },
        ));
        
        $actual = $this->response->matchLayout();
        $this->assertSame('bar', $actual);
    }

    public function testMatchLayout_noAcceptableLayout()
    {
        $this->setExpectedException('aura\web\Exception_NoAcceptableLayout');
        
        $this->response->setContentType('application/xhtml+xml');
        
        $this->response->setLayout(array(
            'text/html'        => 'layout',
            'application/json' => 'layout.json',
            'application/xml'  => 'layout.xml',
        ));
        
        $this->response->matchLayout();
    }
}
