<?php
namespace Aura\Web;

/**
 * Test class for Response.
 * Generated by PHPUnit on 2011-05-02 at 10:30:39.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    protected $response;

    protected function setUp()
    {
        parent::setUp();
        $this->response = new Response;
    }

    protected function tearDown()
    {
        parent::tearDown();
    }

    public function testDisableCache()
    {
        // "add headers to turn off caching"
        $this->response->disableCache(true);
        $this->assertTrue($this->response->isCacheDisabled());
        $expect = [
          'Pragma' => ['no-cache'],
          'Cache-Control' => [
            'no-store, no-cache, must-revalidate',
            'post-check=0, pre-check=0',
          ],
          'Expires' => ['1'],
        ];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
        
        // "do not add cache-related headers"
        $this->response->disableCache(false);
        $this->assertFalse($this->response->isCacheDisabled());
        $expect = [];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    public function testSetAndGetContent()
    {
        $expect = 'foo bar baz';
        $this->response->setContent($expect);
        $actual = $this->response->getContent();
        $this->assertSame($expect, $actual);
    }

    public function testSetAndGetContentType()
    {
        $expect = 'application/json';
        $this->response->setContentType($expect);
        $actual = $this->response->getContentType();
        $this->assertSame($expect, $actual);
        
        $expect = [
          'Content-Type' => ['application/json'],
        ];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    public function testSetAndGetCookie()
    {
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        
        $expect = [
          'value' => 'bar',
          'expire' => $expire,
          'path' => '/path',
          'domain' => 'example.com',
          'secure' => false,
          'httponly' => true,
        ];

        $actual = $this->response->getCookie('foo');
        
        $this->assertSame($expect, $actual);
    }

    public function testGetCookies()
    {
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        $this->response->setCookie('baz', 'dib', date('Y-m-d H:i:s', $expire), '/path', 'example.com');
        
        $expect = [
            'foo' => [
              'value' => 'bar',
              'expire' => $expire,
              'path' => '/path',
              'domain' => 'example.com',
              'secure' => false,
              'httponly' => true,
            ],
            'baz' => [
              'value' => 'dib',
              'expire' => $expire,
              'path' => '/path',
              'domain' => 'example.com',
              'secure' => false,
              'httponly' => true,
            ],
        ];

        $actual = $this->response->getCookies();
        
        $this->assertSame($expect, $actual);
    }

    public function testSetCookiesHttponly()
    {
        $this->response->setCookiesHttponly(false);
        
        $expire = time() + 3600;
        $this->response->setCookie('foo', 'bar', $expire, '/path', 'example.com');
        
        $expect = [
          'value' => 'bar',
          'expire' => $expire,
          'path' => '/path',
          'domain' => 'example.com',
          'secure' => false,
          'httponly' => false,
        ];

        $actual = $this->response->getCookie('foo');
        
        $this->assertSame($expect, $actual);
    }

    public function testSetHeader()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->setHeader('dib', 'zim');
        
        $expect = [
            'Foo-Bar' => ['baz'],
            'Dib' => ['zim'],
        ];
        
        $actual = $this->response->getHeaders();
        
        $this->assertSame($expect, $actual);
    }

    public function testAddHeader()
    {
        $this->response->addHeader('foo', 'bar');
        $this->response->addHeader('foo', 'baz');
        $this->response->addHeader('foo', 'dib');
        
        $expect = [
            'Foo' => ['bar', 'baz', 'dib'],
        ];
        
        $actual = $this->response->getHeaders();
        
        $this->assertSame($expect, $actual);
    }

    public function testGetHeader()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->addHeader('dib', 'zim');
        $this->response->addHeader('dib', 'gir');
        
        $expect = ['baz'];
        $actual = $this->response->getHeader('foo-bar');
        $this->assertSame($expect, $actual);
        
        $expect = ['zim', 'gir'];
        $actual = $this->response->getHeader('dib');
        $this->assertSame($expect, $actual);
        
        // no such header
        $this->assertNull($this->response->getHeader('no-such-header'));
    }

    public function testGetHeaders()
    {
        $this->response->setHeader('foo-bar', 'baz');
        $this->response->addHeader('dib', 'zim');
        $this->response->addHeader('dib', 'gir');
        
        $expect = [
          'Foo-Bar' => ['baz'],
          'Dib' => [
            0 => 'zim',
            1 => 'gir',
          ],
        ];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    public function testRedirect()
    {
        $this->assertFalse($this->response->isRedirect());
        $this->response->setRedirect('http://example.com');
        $this->assertTrue($this->response->isRedirect());
        
        $expect = 'http://example.com';
        $actual = $this->response->getRedirect();
        $this->assertSame($expect, $actual);
        
        $expect = [
          'Location' => ['http://example.com'],
        ];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }
    
    public function testRedirectAfterPost()
    {
        $this->assertFalse($this->response->isRedirect());
        $this->response->setRedirectAfterPost('http://example.com');
        $this->assertTrue($this->response->isRedirect());
        
        $expect = 'http://example.com';
        $actual = $this->response->getRedirect();
        $this->assertSame($expect, $actual);
        
        $expect = [
          'Pragma' => ['no-cache'],
          'Cache-Control' => 
          [
            0 => 'no-store, no-cache, must-revalidate',
            1 => 'post-check=0, pre-check=0',
          ],
          'Expires' => ['1'],
          'Location' => ['http://example.com'],
        ];
        $actual = $this->response->getHeaders();
        $this->assertSame($expect, $actual);
    }

    public function testSetStatus()
    {
        $this->response->setStatus(404, 'Not Found');
        $this->assertSame(404, $this->response->getStatusCode());
        $this->assertSame('Not Found', $this->response->getStatusText());
    }
    
    public function testSetAndGetStatusCode()
    {
        $expect = 404;
        $this->response->setStatusCode($expect);
        $actual = $this->response->getStatusCode();
        $this->assertSame($expect, $actual);
    }
    
    public function testSetStatusCodeWrong()
    {
        $this->setExpectedException('Aura\Web\Exception\InvalidStatusCode');
        $this->response->setStatusCode('88');
    }
    
    public function testSetAndGetStatusText()
    {
        $expect = 'Not Found';
        $this->response->setStatusText($expect);
        $actual = $this->response->getStatusText();
        $this->assertSame($expect, $actual);
    }

    public function testSetAndGetVersion()
    {
        $expect = '1.1';
        $this->response->setVersion($expect);
        $actual = $this->response->getVersion();
        $this->assertSame($expect, $actual);
    }

    public function testVersionWrong()
    {
        $this->setExpectedException('Aura\Web\Exception\InvalidVersion');
        $this->response->setVersion('88');
    }
}
